# Generated by Django 4.2.3 on 2023-07-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=235, verbose_name='Course name')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='Course preview')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Course description')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=235, verbose_name='Lesson name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Lesson description')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='lessons/', verbose_name='Lesson preview')),
                ('video_link', models.URLField(blank=True, max_length=235, null=True, verbose_name='Video link')),
            ],
            options={
                'verbose_name': 'lesson',
                'verbose_name_plural': 'lessons',
            },
        ),
    ]
